In [1]:
import torch

In [2]:
class NeuralNetwork(torch.nn.Module):
    def __init__(self, num_inputs, num_outputs):
        super().__init__()
        
        self.layers = torch.nn.Sequential(
            
            # 1st hidden layer
            torch.nn.Linear(num_inputs, 30),
            torch.nn.ReLU(),
            
            # 2nd hidden layer
            torch.nn.Linear(30, 20),
            torch.nn.ReLU(),
            
            torch.nn.Linear(20, num_outputs)
        )

    def forward(self, x):
        logits = self.layers(x)
        return logits

In [3]:
# We can then instantiate a new neural network object as follows:
model = NeuralNetwork(50, 3)

In [4]:
model

NeuralNetwork(
  (layers): Sequential(
    (0): Linear(in_features=50, out_features=30, bias=True)
    (1): ReLU()
    (2): Linear(in_features=30, out_features=20, bias=True)
    (3): ReLU()
    (4): Linear(in_features=20, out_features=3, bias=True)
  )
)

In [5]:
# Next, let's check the total number of trainable parameters of this model:
total_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
print(f"Total number of trainable parameters: {total_params}")

Total number of trainable parameters: 2213


In [6]:
model.layers[0].weight

Parameter containing:
tensor([[-0.0755, -0.0438,  0.0743,  ...,  0.0683,  0.1343,  0.0441],
        [-0.0298,  0.0697,  0.0925,  ...,  0.0135, -0.0558, -0.0627],
        [-0.1302,  0.0924, -0.1081,  ..., -0.0685,  0.1036, -0.0301],
        ...,
        [ 0.1367, -0.0930,  0.0437,  ...,  0.0723, -0.0430, -0.0330],
        [ 0.0274, -0.0950,  0.0173,  ..., -0.1088,  0.0357, -0.0295],
        [ 0.0758,  0.0684, -0.0030,  ..., -0.0868, -0.0354, -0.0106]],
       requires_grad=True)

In [9]:
# We can access the corresponding weight parameter matrix as follows:
model.layers[0].weight.shape

torch.Size([30, 50])

In [10]:
# Similarly, you could access the bias vector via:
model.layers[0].bias

Parameter containing:
tensor([-0.0567,  0.0229, -0.1345,  0.0381,  0.0560, -0.1380, -0.0764, -0.0375,
         0.1194, -0.1319,  0.1254,  0.0228, -0.1001, -0.0110, -0.0269,  0.0645,
         0.0915,  0.1184, -0.1414, -0.1292, -0.1388, -0.0964, -0.0425,  0.1172,
        -0.1060, -0.0412, -0.0359,  0.1085,  0.1100, -0.0190],
       requires_grad=True)

# We want to keep using small random numbers as initial values for our layer weights, we can make the random number initialization reproducible by seeding PyTorch's random number generator via

In [11]:
torch.manual_seed(123)
model = NeuralNetwork(50, 3)
model.layers[0].weight

Parameter containing:
tensor([[-0.0577,  0.0047, -0.0702,  ...,  0.0222,  0.1260,  0.0865],
        [ 0.0502,  0.0307,  0.0333,  ...,  0.0951,  0.1134, -0.0297],
        [ 0.1077, -0.1108,  0.0122,  ...,  0.0108, -0.1049, -0.1063],
        ...,
        [-0.0787,  0.1259,  0.0803,  ...,  0.1218,  0.1303, -0.1351],
        [ 0.1359,  0.0175, -0.0673,  ...,  0.0674,  0.0676,  0.1058],
        [ 0.0790,  0.1343, -0.0293,  ...,  0.0344, -0.0971, -0.0509]],
       requires_grad=True)

In [12]:
#  let's briefly see how it's used via the forward pass:
torch.manual_seed(123)
x_rand = torch.rand(1, 50)
out = model(x_rand)
out

tensor([[-0.1262,  0.1080, -0.1792]], grad_fn=<AddmmBackward0>)

In [15]:
# If we just want to use a network without training or backpropagation
with torch.no_grad():
    out = model(x_rand)
    print(out)

tensor([[-0.1262,  0.1080, -0.1792]])


In [17]:
# if we want to compute class-membership probabilities for our predictions, we have to call the softmax function explicitly:
with torch.no_grad():
    out = torch.softmax(model(x_rand), dim=1)
    print(out)

tensor([[0.3113, 0.3934, 0.2952]])
