In [5]:
import torch
tensor0d = torch.tensor(1)

tensor1d = torch.tensor([1, 2, 3])

tensor2d = torch.tensor([[1, 2], [4, 5]])

tensor3d = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

In [6]:
print(tensor1d.dtype)

torch.int64


In [7]:
float_tensor = torch.tensor([1.0, 2.0, 3.0])
print(float_tensor.dtype)

torch.float32


In [12]:
tensor1_float = tensor1d.to(torch.float32)
print(tensor1_float.dtype)
print(tensor1_float.shape)
print(tensor2d.shape)
print(tensor3d.shape)

torch.float32
torch.Size([3])
torch.Size([2, 2])
torch.Size([2, 2, 2])


In [18]:
tensor4 =  torch.tensor([[1, 2, 3], [4, 5, 6]])
print(tensor4.shape)
tensor4

torch.Size([2, 3])


tensor([[1, 2, 3],
        [4, 5, 6]])

In [16]:
tensor4_reshaped = tensor4.reshape(3, 2)
tensor4_reshaped

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [17]:
tensor4.T

tensor([[1, 4],
        [2, 5],
        [3, 6]])

In [19]:
tensor4 @ tensor4.T

tensor([[14, 32],
        [32, 77]])